version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8082
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      netjenkins:
        ipv4_address: 172.130.12.2
volumes:
  jenkins:
networks:
  netjenkins:
    ipam: 
      driver: default
      config: 
          - subnet: 172.130.12.0/24